name: pokeledger
description: An app that integrates PokeAPI.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dartz: ^0.10.1
  provider: ^6.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.6.0
  shimmer: ^2.0.0
  connectivity: ^3.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  injectable_generator: ^1.5.2
  mockito: ^5.2.0
  bloc_test: ^9.0.3
  json_serializable: ^6.3.1
  freezed: ^1.1.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 500
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
